import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import * as enums from "@/api/types/portfolio/enums";
import type { Profile } from "@/api/types/portfolio/profile";
import type { Project } from "@/api/types/portfolio/project";
import { layoutBlocks } from "./layout";
import { parseMe, type ParsedMe } from "./parse";
import { buildSeed } from "./seed";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const sourcePath = resolve(root, "content/ME.md");
const outDir = resolve(root, "src/api/mocks/portfolio");
const seedPath = resolve(root, "content/seed.json");
const generated =
	"// Generated by scripts/build-portfolio/index.ts from content/ME.md. Edit the source, then run bun run build:portfolio.";

const NAME = "William Siefert";
const HEADLINE = "Software engineer";
const CONTACT = {
	email: "wilhelm.hsf@gmail.com",
	github: "https://github.com/king-glitch",
	linkedin: "https://www.linkedin.com/in/william-siefert",
	discord: "rachamon",
};

export function buildProfile(me: ParsedMe): Profile {
	return {
		name: NAME,
		headline: HEADLINE,
		about: me.about,
		skills: me.skills,
		core: me.core,
		experience: me.experience,
		education: me.education,
		contact: CONTACT,
	};
}

export function buildProjects(me: ParsedMe): Project[] {
	return me.projects.map((p) => ({
		id: p.id,
		num: p.num,
		name: p.name,
		full: p.full,
		kind: p.kind,
		side: p.side,
		tags: p.tags,
		categories: p.categories,
		stack: p.stack,
		about: p.about,
		role: p.role,
		blocks: layoutBlocks(p),
	}));
}

/** Property name -> the enum its string values come from, so fixtures are emitted as `Enum.Member`, never as literals. */
const ENUM_BY_KEY: Record<string, Record<string, string>> = {
	type: enums.BlockType,
	variant: enums.HeaderVariant,
	screen: enums.MockScreen,
	view: enums.DeviceView,
	discipline: enums.ProjectSide,
	side: enums.ProjectSide,
	tone: enums.BlockTone,
};

function enumRef(
	enumObject: Record<string, string>,
	enumName: string,
	value: string,
): string {
	const member = Object.entries(enumObject).find(([, v]) => v === value)?.[0];
	if (!member) throw new Error(`${value} is not a member of ${enumName}`);
	return `${enumName}.${member}`;
}

const ENUM_NAMES = new Map<Record<string, string>, string>(
	Object.entries(enums).map(([name, e]) => [e, name]),
);

/** Serialises plain data as TS source, replacing enum values by `Enum.Member` references. */
export function toTs(
	value: unknown,
	key = "",
	kindEnum: Record<string, string> = enums.MotifKind,
): string {
	if (Array.isArray(value))
		return `[${value.map((v) => toTs(v, key, kindEnum)).join(",")}]`;
	if (value && typeof value === "object") {
		const fields = Object.entries(value).map(
			([k, v]) => `${JSON.stringify(k)}:${toTs(v, k, kindEnum)}`,
		);
		return `{${fields.join(",")}}`;
	}
	if (typeof value === "string") {
		const table = key === "kind" ? kindEnum : ENUM_BY_KEY[key];
		if (table) return enumRef(table, ENUM_NAMES.get(table) ?? key, value);
	}
	return JSON.stringify(value);
}

function file(
	imports: string[],
	typeImport: string,
	name: string,
	type: string,
	body: string,
): string {
	const used = [
		...new Set(body.match(/\b[A-Z][A-Za-z]+(?=\.[A-Z])/g) ?? []),
	].sort();
	return [
		generated,
		`import { ${used.join(", ")} } from "@/api/types/portfolio/enums";`,
		...imports,
		typeImport,
		`export const ${name}: ${type} = ${body};`,
		"",
	].join("\n");
}

export function buildFiles(me: ParsedMe): Record<string, string> {
	return {
		"profile.ts": file(
			[],
			`import type { Profile } from "@/api/types/portfolio/profile";`,
			"profile",
			"Profile",
			toTs(buildProfile(me), "", enums.ExperienceKind),
		),
		"projects.ts": file(
			[],
			`import type { Project } from "@/api/types/portfolio/project";`,
			"projects",
			"Project[]",
			toTs(buildProjects(me)),
		),
	};
}

async function prettyWrite(path: string, code: string) {
	const options = await resolveConfig(path);
	await writeFile(
		path,
		await format(code, { ...options, filepath: path }),
		"utf8",
	);
}

if (import.meta.main) {
	const me = parseMe(await readFile(sourcePath, "utf8"));
	await mkdir(outDir, { recursive: true });
	for (const [name, code] of Object.entries(buildFiles(me)))
		await prettyWrite(resolve(outDir, name), code);
	await prettyWrite(
		seedPath,
		JSON.stringify(buildSeed(buildProjects(me), buildProfile(me))),
	);
	console.log(`Generated ${me.projects.length} projects -> ${outDir}`);
}
