import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const currentDir = dirname(fileURLToPath(import.meta.url));
const root = resolve(currentDir, "../..");
const configPath = resolve(currentDir, "configs/theme.json");
const outputCssPath = resolve(root, "src/theme/tokens.css");
const outputTsPath = resolve(root, "src/theme/tokens.ts");
const generated =
	"Generated by scripts/build-token/index.ts. Edit scripts/build-token/configs/theme.json, then run bun run build:tokens.";

type Mode = "light" | "dark" | "shared";
const modes: readonly Mode[] = ["light", "dark", "shared"];

type TokenTree = { $value?: string | number } & {
	[key: string]: TokenTree | string | number | undefined;
};

interface CollectedToken {
	path: string[];
	value: string | number;
}

const rawConfig: Record<string, TokenTree> = JSON.parse(
	await readFile(configPath, "utf8"),
);

function collect(
	node: TokenTree,
	path: string[],
	into: CollectedToken[],
): void {
	if (node.$value !== undefined) {
		into.push({ path, value: node.$value });
		return;
	}
	for (const [key, child] of Object.entries(node)) {
		if (key.startsWith("$") || typeof child !== "object") continue;
		collect(child, [...path, key], into);
	}
}

const byMode = new Map<Mode, CollectedToken[]>();
for (const mode of modes) {
	const tokens: CollectedToken[] = [];
	const tree = rawConfig[mode];
	if (tree) collect(tree, [], tokens);
	byMode.set(mode, tokens);
}

const cssName = (path: string[]) => `--${path.join("-")}`;
const declarations = (mode: Mode) =>
	(byMode.get(mode) ?? []).map(
		({ path, value }) => `\t${cssName(path)}: ${value};`,
	);

const cssOutput = [
	`/* ${generated} */`,
	":root {",
	...declarations("light"),
	...declarations("shared"),
	"}",
	"",
	".dark {",
	...declarations("dark"),
	"}",
	"",
].join("\n");

const tsTokens: Record<string, string> = {};
for (const mode of modes) {
	for (const { path } of byMode.get(mode) ?? []) {
		tsTokens[path.join("-")] = `var(${cssName(path)})`;
	}
}

const tsOutput = [
	`/* ${generated} */`,
	`export const designTokens = ${JSON.stringify(tsTokens, null, 2)} as const;`,
	"",
	"export type DesignTokens = typeof designTokens;",
	"",
].join("\n");

await mkdir(dirname(outputCssPath), { recursive: true });
// Match `bun run pretty` so regenerating tokens never dirties the tree.
async function prettyWrite(path: string, code: string) {
	const options = await resolveConfig(path);
	await writeFile(
		path,
		await format(code, { ...options, filepath: path }),
		"utf8",
	);
}
await prettyWrite(outputCssPath, cssOutput);
await prettyWrite(outputTsPath, tsOutput);

const total = modes.reduce((n, m) => n + (byMode.get(m)?.length ?? 0), 0);
console.log(
	`Generated ${total} tokens -> ${outputCssPath} and ${outputTsPath}`,
);
