// Generated by scripts/build-portfolio/index.ts from content/ME.md. Edit the source, then run bun run build:portfolio.
import { ExperienceKind } from "@/api/types/portfolio/enums";
import type { Profile } from "@/api/types/portfolio/profile";
export const profile: Profile = {
	name: "William Siefert",
	headline: "Software engineer",
	about: "Hi, I’m William, or Tiger. I write Go and TypeScript, mostly the kind with sockets, queues and smart contracts behind it. I like systems that are general, dynamic and still standing when traffic triples, and I build the simple front end on top because a clean UI is half of a reliable product. I learned by building, breaking and rebuilding. Off the clock: games, green tea and too much Reddit.",
	skills: [
		{
			label: "Programming Languages",
			items: [
				"Golang",
				"Typescript",
				"Solidity",
				"Python",
				"PHP",
				"Java",
				"C#",
			],
		},
		{
			label: "Frameworks and Libraries",
			items: ["MongoDB", "SQL", "React"],
		},
		{
			label: "Tools and Technologies",
			items: [
				"Git",
				"Docker",
				"AWS",
				"Google Cloud Platform",
				"Web3",
				"Blockchain",
			],
		},
		{
			label: "Soft Skills",
			items: [
				"Problem-solving",
				"Time Management",
				"Communication",
				"Teamwork",
			],
		},
		{
			label: "Hardskills",
			items: [
				"Backend Development",
				"Server-side Development",
				"Smart Contract Development",
				"Socket Communication",
				"Performance Optimization",
				"Scalability",
				"Security Measures",
			],
		},
	],
	core: [
		{
			label: "Backend Development",
			text: "General, dynamic servers that scale with traffic and keep data safe.",
		},
		{
			label: "Smart Contract Development",
			text: "Solidity contracts for games and apps on Soneium and Bitkub, written with security in mind from the first line.",
		},
		{
			label: "Socket Communication",
			text: "Real-time links between players and servers, so every screen shows the same thing at the same moment.",
		},
		{
			label: "Performance Optimization",
			text: "Measuring first, then fixing the slow parts of code and architecture without breaking the rest.",
		},
		{
			label: "Security Measures",
			text: "Encryption, authentication and careful coding, so the only people inside are the ones invited.",
		},
	],
	experience: [
		{
			id: "software-engineer-x10-interactive",
			title: "Software Engineer X10 Interactive",
			period: "2023 — Present",
			notes: [
				"Build and look after game servers, web apps and blockchain products on the Soneium and Bitkub chains, from the first prototype to live launches.",
				"Keep quality high with code reviews and tests, and ship alongside designers, client developers and product people.",
			],
			kind: ExperienceKind.Work,
			start: "2023-01",
			end: null,
		},
		{
			id: "fullstack-developer-intern-bangkok-university-multimedia-intelligent-technology",
			title: "Fullstack Developer Intern Bangkok University Multimedia Intelligent Technology",
			period: "June 2022 — June 2023",
			notes: [
				"Interned in the university research lab, building AADS, a military air defence system, and the School Bus Backend and Administration System.",
			],
			kind: ExperienceKind.Work,
			start: "2022-06",
			end: "2023-06",
		},
	],
	education: [
		{
			id: "bangkok-university",
			title: "Bangkok University",
			period: "2019 — 2023",
			notes: [
				"Bachelor of Science in Computer Science, majoring in multimedia intelligent technology. GPA 3.90. Senior project: the School Bus Backend and Administration System.",
			],
			kind: ExperienceKind.Education,
			start: "2019-01",
			end: "2023-01",
		},
	],
	contact: {
		email: "wilhelm.hsf@gmail.com",
		github: "https://github.com/king-glitch",
		linkedin: "https://www.linkedin.com/in/william-siefert",
		discord: "rachamon",
	},
};
