// Generated by scripts/build-portfolio/index.ts from content/ME.md. Edit the source, then run bun run build:portfolio.
import { ExperienceKind } from "@/api/types/portfolio/enums";
import type { Profile } from "@/api/types/portfolio/profile";
export const profile: Profile = {
	name: "William Siefert",
	headline: "Software developer",
	about: "I’m William. I build the parts of apps and games you never see — the bits that keep everything quick, fair and online when a lot of people show up at once. I like hard problems, short feedback loops, and leaving code a little nicer than I found it.",
	skills: [
		{
			label: "Programming Languages",
			items: [
				"Golang",
				"Typescript",
				"Solidity",
				"Python",
				"PHP",
				"Java",
				"C#",
			],
		},
		{
			label: "Frameworks and Libraries",
			items: ["MongoDB", "SQL", "React"],
		},
		{
			label: "Tools and Technologies",
			items: [
				"Git",
				"Docker",
				"AWS",
				"Google Cloud Platform",
				"Web3",
				"Blockchain",
			],
		},
		{
			label: "Soft Skills",
			items: [
				"Problem-solving",
				"Time Management",
				"Communication",
				"Teamwork",
			],
		},
		{
			label: "Hardskills",
			items: [
				"Backend Development",
				"Server-side Development",
				"Smart Contract Development",
				"Socket Communication",
				"Performance Optimization",
				"Scalability",
				"Security Measures",
			],
		},
	],
	core: [
		{
			label: "Backend Development",
			text: "Server-side apps that stay fast, scale with traffic and keep data safe.",
		},
		{
			label: "Smart Contract Development",
			text: "Solidity contracts for games and apps, written with security in mind from the first line.",
		},
		{
			label: "Socket Communication",
			text: "Real-time links between players and servers, so every screen shows the same thing at the same moment.",
		},
		{
			label: "Performance Optimization",
			text: "Finding the slow parts of code and architecture, and fixing them without breaking anything else.",
		},
		{
			label: "Security Measures",
			text: "Encryption, authentication and careful coding, so the only people inside are the ones invited.",
		},
	],
	experience: [
		{
			id: "bangkok-university-multimedia-intelligent-technology",
			title: "Bangkok University Multimedia Intelligent Technology",
			period: "June 2022 — June 2023",
			notes: [
				"Worked on student research projects in multimedia and intelligent technology, including AADS (an air defence system for the army) and a school bus tracking system.",
			],
			kind: ExperienceKind.Work,
			start: "2022-06",
			end: "2023-06",
		},
		{
			id: "software-developer-x10-interactive",
			title: "Software Developer X10 Interactive",
			period: "2023 — Present",
			notes: [
				"Build and look after web apps, game servers and blockchain products, from the first prototype to live launches.",
				"Keep quality high with code reviews and tests, and ship on time alongside designers, client developers and product people.",
			],
			kind: ExperienceKind.Work,
			start: "2023-01",
			end: null,
		},
	],
	education: [
		{
			id: "bangkok-university",
			title: "Bangkok University",
			period: "2019 — 2023",
			notes: [
				"Bachelor of Science in Computer Science, majoring in multimedia intelligent technology. Four years of fundamentals plus hands-on research projects, which is where I learned to enjoy the hard parts.",
			],
			kind: ExperienceKind.Education,
			start: "2019-01",
			end: "2023-01",
		},
	],
	contact: {
		email: "wilhelm.hsf@gmail.com",
		github: "https://github.com/king-glitch",
		linkedin: "https://www.linkedin.com/in/william-siefert",
	},
};
