// Generated by scripts/build-portfolio/index.ts from content/ME.md. Edit the source, then run bun run build:portfolio.
import { ExperienceKind } from "@/api/types/portfolio/enums";
import type { Profile } from "@/api/types/portfolio/profile";
export const profile: Profile = {
	name: "William Siefert",
	headline: "Software developer",
	about: "My name is William Siefert, and I am a software developer with a passion for creating innovative solutions to complex problems. With a strong background in computer science and experience in various programming languages, I have developed a diverse skill set that allows me to tackle a wide range of projects. I am always eager to learn new technologies and stay up-to-date with industry trends, which helps me to continuously improve my skills and deliver high-quality work.",
	skills: [
		{
			label: "Programming Languages",
			items: [
				"Golang",
				"Typescript",
				"Solidity",
				"Python",
				"PHP",
				"Java",
				"C#",
			],
		},
		{
			label: "Frameworks and Libraries",
			items: ["MongoDB", "SQL", "React"],
		},
		{
			label: "Tools and Technologies",
			items: [
				"Git",
				"Docker",
				"AWS",
				"Google Cloud Platform",
				"Web3",
				"Blockchain",
			],
		},
		{
			label: "Soft Skills",
			items: [
				"Problem-solving",
				"Time Management",
				"Communication",
				"Teamwork",
			],
		},
		{
			label: "Hardskills",
			items: [
				"Backend Development",
				"Server-side Development",
				"Smart Contract Development",
				"Socket Communication",
				"Performance Optimization",
				"Scalability",
				"Security Measures",
			],
		},
	],
	core: [
		{
			label: "Backend Development",
			text: "Proficient in developing server-side applications using various programming languages and frameworks, with a focus on performance optimization, scalability, and security measures.",
		},
		{
			label: "Smart Contract Development",
			text: "Experienced in developing smart contracts using Solidity for blockchain-based applications, with a strong understanding of blockchain technology and security considerations.",
		},
		{
			label: "Socket Communication",
			text: "Skilled in implementing socket communication for real-time updates and interactions between clients and servers, ensuring optimized performance and reliability.",
		},
		{
			label: "Performance Optimization",
			text: "Adept at optimizing code and system architecture to improve performance and scalability, while also ensuring the security and reliability of the applications.",
		},
		{
			label: "Security Measures",
			text: "Knowledgeable in implementing security measures to protect applications and data, including encryption, authentication, and secure coding practices.",
		},
	],
	experience: [
		{
			id: "bangkok-university-multimedia-intelligent-technology",
			title: "Bangkok University Multimedia Intelligent Technology",
			period: "June 2022 — June 2023",
			notes: [
				"As a student, I have been actively involved in various projects and research related to multimedia intelligent technology. During my time at the university, I have been working on various projects, including AADS (Army Air Defense System), School Bus Tracking System.",
			],
			kind: ExperienceKind.Work,
			start: "2022-06",
			end: "2023-06",
		},
		{
			id: "software-developer-x10-interactive",
			title: "Software Developer X10 Interactive",
			period: "2023 — Present",
			notes: [
				"Developed and maintained various software applications, including web applications, and blockchain-based solutions.",
				"Implemented best practices for software development, including code reviews, testing to ensure the quality and reliability of the software, and collaborated with cross-functional teams to deliver high-quality products on time.",
			],
			kind: ExperienceKind.Work,
			start: "2023-01",
			end: null,
		},
	],
	education: [
		{
			id: "bangkok-university",
			title: "Bangkok University",
			period: "2019 — 2023",
			notes: [
				"Bachelor of Science in Computer Science, with a focus on multimedia intelligent technology. During my time at the university, I have gained a strong foundation in computer science principles and have had the opportunity to work on various projects and research related to multimedia intelligent technology, which has helped me to develop my skills and knowledge in this field.",
			],
			kind: ExperienceKind.Education,
			start: "2019-01",
			end: "2023-01",
		},
	],
	contact: {
		email: "[YOUR EMAIL]",
		github: "[GITHUB]",
		linkedin: "[LINKEDIN]",
	},
};
