// Generated by scripts/build-portfolio/index.ts from content/ME.md. Edit the source, then run bun run build:portfolio.
import {
	BlockType,
	MediaFit,
	MediaTone,
	MotifKind,
	ProjectLifecycle,
	ProjectSide,
} from "@/api/types/portfolio/enums";
import type { Project } from "@/api/types/portfolio/project";
export const projects: Project[] = [
	{
		id: "morning-moon-pocket",
		num: "0001",
		name: "Morning Moon Pocket",
		full: "Morning Moon Pocket",
		kind: MotifKind.Pixel,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "MongoDB", "Solidity", "Soneium", "Mini app"],
		categories: ["games", "on-chain"],
		stack: ["golang", "mongodb", "solidity", "soneium"],
		about: "Morning Moon Village, folded into a pocket. A cozy farming RPG that opens instantly as a mini app on Soneium: plant, fish, fight, craft, raise pets, and farm real on-chain yield in between.",
		role: [
			"Rewrote the whole server in Golang and MongoDB, with a new database schema and leaner code paths, built for many more players than the original game.",
			"Built the shop and mission systems on the new architecture.",
			"Rewrote most of the Solidity smart contracts for Soneium, keeping them safe and efficient.",
			"Kept every old feature working through the rewrite, in lockstep with the client team.",
		],
		artUrl: "/projects/morning-moon-pocket/cover.webp",
		position: "Software Engineer",
		period: "9 months",
		team: "X10 Interactive",
		lifecycle: ProjectLifecycle.Live,
		platforms: ["Startale App mini app", "Web browser"],
		chains: ["Soneium"],
		links: [
			{
				label: "morningmoonpocket.com",
				url: "https://morningmoonpocket.com",
			},
			{ label: "@MMPgame on X", url: "https://x.com/MMPgame" },
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: { tagline: "The farm, rebuilt for phones." },
			},
			{ type: BlockType.Overview, params: { label: "Overview" } },
			{
				type: BlockType.Filmstrip,
				params: {
					label: "Screens",
					caption: "Real captures from the live mini app",
					items: [
						{
							url: "/projects/morning-moon-pocket/farm.webp",
							alt: "A farmhouse with barrels and a tomato patch",
							caption: "Your farm",
							width: 925,
							height: 1190,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
						{
							url: "/projects/morning-moon-pocket/crops.webp",
							alt: "Farm management panel for a tomato plot",
							caption: "Farm management",
							width: 970,
							height: 1910,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
						{
							url: "/projects/morning-moon-pocket/gather.webp",
							alt: "A player chopping a tree in the forest",
							caption: "Gathering",
							width: 960,
							height: 1860,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
						{
							url: "/projects/morning-moon-pocket/shop.webp",
							alt: "The Mayor's shop with potions, soups and tools",
							caption: "The shop I built",
							width: 970,
							height: 1420,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
					],
				},
			},
			{
				type: BlockType.Contributions,
				params: { label: "What I built" },
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Mini app",
							description: "Startale App and the browser",
						},
						{
							name: "Go services",
							description: "Farm loop, shop, missions",
						},
						{
							name: "MongoDB",
							description: "New schema for players and items",
						},
						{
							name: "Soneium",
							description:
								"Solidity contracts for yield and items",
						},
					],
				},
			},
			{
				type: BlockType.Challenge,
				params: {
					label: "The hard part",
					items: [
						{
							problem:
								"More players, the same feel, and a short deadline.",
							approach:
								"Ported feature by feature onto the new schema, with the old behaviour as the spec, agreed with the client team before each switch. The farm plays the same on new plumbing.",
						},
					],
				},
			},
			{
				type: BlockType.Statement,
				params: { text: "Same farm. New plumbing." },
			},
			{
				type: BlockType.Showcase,
				params: {
					label: "The logo",
					url: "/projects/morning-moon-pocket/logo.webp",
					alt: "Morning Moon Pocket logo",
					caption: "Morning Moon Pocket",
					width: 711,
					height: 667,
					fit: MediaFit.Contain,
					tone: MediaTone.Photo,
				},
			},
			{
				type: BlockType.Lineage,
				params: {
					label: "Lineage",
					from: "Morning Moon Village",
					fromId: "morning-moon-village",
					to: "Morning Moon Pocket",
					text: "Same farming loop, a pocket-sized client, and a server side rewritten from the ground up.",
				},
			},
			{ type: BlockType.Links, params: { label: "See it" } },
		],
	},
	{
		id: "metal-valley",
		num: "0002",
		name: "Metal Valley",
		full: "Metal Valley",
		kind: MotifKind.Hex,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "WebSocket", "MongoDB", "Solidity", "Bridge"],
		categories: ["games", "on-chain"],
		stack: ["golang", "websocket", "mongodb", "solidity", "bitkub"],
		about: "A creature collector, except the creatures are robots. Mech hunters roam an archipelago, catch wild Autometa, train them and bolt on new parts, then take them on-chain only if they want to. Web2 gameplay first, Web3 ownership optional.",
		role: [
			"Built the Golang WebSocket layer that connects every player to the game world, made to stay fast and secure under load.",
			"Built the capture and training mechanics.",
			"Wrote most of the Solidity smart contracts on Bitkub Chain.",
			"Built the bridge, a website and its backend, that turns in-game items into chain assets and back.",
		],
		artUrl: "/projects/metal-valley/cover.webp",
		position: "Software Engineer",
		period: "2 years",
		team: "X10 Interactive",
		lifecycle: ProjectLifecycle.Live,
		platforms: ["Windows", "Android", "iOS"],
		chains: ["Bitkub Chain"],
		links: [
			{
				label: "metalvalleygame.com",
				url: "https://metalvalleygame.com",
			},
			{ label: "x10.games", url: "https://x10.games" },
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: { tagline: "Mech hunters, on-chain." },
			},
			{ type: BlockType.Overview, params: { label: "Overview" } },
			{
				type: BlockType.Showcase,
				params: {
					label: "The world",
					url: "/projects/metal-valley/city.webp",
					alt: "A purple robot chasing a hunter through a city street",
					caption: "Hunts run from the archipelago into the city",
					width: 2559,
					height: 960,
					fit: MediaFit.Cover,
					tone: MediaTone.Photo,
				},
			},
			{
				type: BlockType.Contributions,
				params: { label: "What I built" },
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Game client",
							description: "Explore, capture, train",
						},
						{
							name: "Socket server",
							description: "Go, real-time, many players",
						},
						{
							name: "API server",
							description: "Go, accounts and inventory",
						},
						{
							name: "MongoDB",
							description: "One shared state for both servers",
						},
						{
							name: "Bridge",
							description: "Game items to chain assets and back",
						},
					],
				},
			},
			{
				type: BlockType.Filmstrip,
				params: {
					label: "Screens",
					caption: "In-game captures",
					items: [
						{
							url: "/projects/metal-valley/coast.webp",
							alt: "Hunters with their mechs on a sunny coast",
							caption: "The coast",
							width: 1920,
							height: 1080,
							fit: MediaFit.Cover,
							tone: MediaTone.Photo,
						},
						{
							url: "/projects/metal-valley/lake.webp",
							alt: "A hunter on a raft in a glowing lake",
							caption: "The lake",
							width: 1700,
							height: 955,
							fit: MediaFit.Cover,
							tone: MediaTone.Photo,
						},
						{
							url: "/projects/metal-valley/meadow.webp",
							alt: "A hunter resting in a meadow beside a robot",
							caption: "Downtime",
							width: 1700,
							height: 955,
							fit: MediaFit.Cover,
							tone: MediaTone.Photo,
						},
						{
							url: "/projects/metal-valley/flight.webp",
							alt: "A green mech flying over a floating island",
							caption: "Flight",
							width: 2556,
							height: 957,
							fit: MediaFit.Cover,
							tone: MediaTone.Photo,
						},
					],
				},
			},
			{
				type: BlockType.Challenge,
				params: {
					label: "The hard part",
					items: [
						{
							problem:
								"Real-time sockets for many players at once, without opening holes.",
							approach:
								"The socket server owns the state and clients only send intent, so it stays fast, authoritative and hard to cheat.",
						},
						{
							problem:
								"The socket server and the API server must agree on the game state.",
							approach:
								"Both read and write the same MongoDB: one source of truth, no sync protocol to break.",
						},
						{
							problem:
								"Moving items between a game database and a chain.",
							approach:
								"The bridge backend checks ownership on both sides before it mints or releases anything.",
						},
					],
				},
			},
			{
				type: BlockType.Statement,
				params: { text: "Two servers. One truth." },
			},
			{
				type: BlockType.Showcase,
				params: {
					label: "The hunters",
					url: "/projects/metal-valley/hunters.webp",
					alt: "A hunter with a hammer and three robot companions",
					caption: "A hunter and the Autometa he caught",
					width: 1541,
					height: 1600,
					fit: MediaFit.Contain,
					tone: MediaTone.Photo,
				},
			},
			{ type: BlockType.Links, params: { label: "See it" } },
		],
	},
	{
		id: "evermoon-socialfi",
		num: "0003",
		name: "Evermoon SocialFi",
		full: "Evermoon SocialFi",
		kind: MotifKind.Orbit,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "MongoDB", "Quest engine", "SocialFi"],
		categories: ["platforms", "on-chain"],
		stack: ["golang", "mongodb"],
		about: "Moon Mission was the quest hub for Evermoon, a 5v5 Web3 MOBA. Players took on monthly quests and social tasks, earned Moon Power (XP), and climbed toward $EVM tokens and NFTs. It ran for a season, then closed, as planned.",
		role: [
			"Built the server side in Golang and MongoDB.",
			"Built the mission system and its quest engine: monthly quests plus social-task verification.",
		],
		artUrl: "/projects/evermoon-socialfi/cover.webp",
		position: "Backend developer",
		period: "2 months",
		team: "Evermoon",
		lifecycle: ProjectLifecycle.Ended,
		platforms: ["Web"],
		chains: [],
		links: [{ label: "evermoon.games", url: "https://evermoon.games" }],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: { tagline: "Quests, Moon Power, two months." },
			},
			{ type: BlockType.Overview, params: { label: "Overview" } },
			{
				type: BlockType.Showcase,
				params: {
					label: "The mascot",
					url: "/projects/evermoon-socialfi/axolt.webp",
					alt: "Axolt, Evermoon's pink axolotl mascot",
					caption: "Axolt, who handed out the quests",
					width: 1381,
					height: 1600,
					fit: MediaFit.Contain,
					tone: MediaTone.Photo,
				},
			},
			{
				type: BlockType.Contributions,
				params: { label: "What I built" },
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Portal",
							description: "Quests, tasks, rewards",
						},
						{
							name: "Quest engine",
							description:
								"Go: monthly quests, social-task checks",
						},
						{
							name: "MongoDB",
							description: "Progress and Moon Power",
						},
					],
				},
			},
			{
				type: BlockType.Challenge,
				params: {
					label: "The hard part",
					items: [
						{
							problem:
								"Two months, many quest types, and a client team building at the same time.",
							approach:
								"One general quest model with many task kinds, and test cases agreed with the client team up front. It shipped on time for the season.",
						},
					],
				},
			},
			{
				type: BlockType.Statement,
				params: { text: "Two months. One engine. Many quests." },
			},
			{
				type: BlockType.Showcase,
				params: {
					label: "The reward",
					url: "/projects/evermoon-socialfi/moon-chest.webp",
					alt: "A glowing capsule in a ring of light",
					caption: "The Moon Chest that quests filled up",
					width: 1920,
					height: 1080,
					fit: MediaFit.Cover,
					tone: MediaTone.Photo,
				},
			},
			{ type: BlockType.Links, params: { label: "See it" } },
		],
	},
	{
		id: "estic-ai",
		num: "0004",
		name: "Estic AI",
		full: "Estic AI",
		kind: MotifKind.Pins,
		side: ProjectSide.OnScreen,
		tags: ["React", "TypeScript", "Leaflet", "Maps", "AI search"],
		categories: ["platforms"],
		stack: ["react", "typescript", "leaflet"],
		about: "A Thai property platform where you describe the life you want and the AI finds homes that fit, backed by hyper-local data on livability, travel and climate risk. In Thai and English.",
		role: [
			"Developed the client side as a freelance frontend developer: the map, the search and the interface, in React and TypeScript.",
			"Made a map of 4,000+ homes stay smooth: it asks the search API only for the pins inside the current view and clusters them on the client.",
			"Laid the UI groundwork first, so new features plug in instead of piling up.",
		],
		artUrl: undefined,
		position: "Frontend developer (freelance)",
		period: "1 year",
		team: "Tetragram",
		lifecycle: ProjectLifecycle.Live,
		platforms: ["Web"],
		chains: [],
		links: [{ label: "estic.ai", url: "https://estic.ai" }],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: { tagline: "Find a home by talking." },
			},
			{ type: BlockType.Overview, params: { label: "Overview" } },
			{
				type: BlockType.Contributions,
				params: { label: "What I built" },
			},
			{
				type: BlockType.Challenge,
				params: {
					label: "The hard part",
					items: [
						{
							problem:
								"4,000+ pins on one map when you zoom all the way out.",
							approach:
								"The map asks the search API only for pins inside the current view and clusters them on the client (Leaflet + markercluster). Zoom in and it drops to about 1,000.",
						},
						{
							problem: "A new product with new patterns.",
							approach:
								"Laid the UI groundwork first, so features plug in instead of piling up.",
						},
					],
				},
			},
			{
				type: BlockType.Statement,
				params: { text: "4,000 pins. One smooth map." },
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Map and chat",
							description: "React, TypeScript, Leaflet",
						},
						{
							name: "Search API",
							description: "AI search over listings",
						},
						{
							name: "Data",
							description: "Homes, livability, climate risk",
						},
					],
				},
			},
			{ type: BlockType.Links, params: { label: "See it" } },
		],
	},
	{
		id: "morning-moon-village",
		num: "0005",
		name: "Morning Moon Village",
		full: "Morning Moon Village",
		kind: MotifKind.Moon,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "MongoDB", "Solidity", "DeFi", "NFTs"],
		categories: ["games", "on-chain"],
		stack: ["golang", "mongodb", "solidity", "bitkub"],
		about: "A 3D farming game with real DeFi yield farming inside. Grow crops, gather, fish and craft, and learn how yield farming works without reading a whitepaper. NFTs add the competition.",
		role: [
			"Learned a Golang backend that had grown for five years under other hands, then extended it.",
			"Built the new shop system and resource spawning.",
			"Connected the game server to the chain, so DeFi and NFTs work in play.",
			"Wrote Solidity smart contracts on Bitkub Chain.",
		],
		artUrl: "/projects/morning-moon-village/cover.webp",
		position: "Software Engineer",
		period: "~3 years",
		team: "X10 Interactive",
		lifecycle: ProjectLifecycle.Live,
		platforms: ["Web (3D)"],
		chains: ["Bitkub Chain"],
		links: [
			{
				label: "morningmoonvillage.com",
				url: "https://morningmoonvillage.com",
			},
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: { tagline: "Farming meets DeFi." },
			},
			{ type: BlockType.Overview, params: { label: "Overview" } },
			{
				type: BlockType.Filmstrip,
				params: {
					label: "Screens",
					caption: "In-game captures",
					items: [
						{
							url: "/projects/morning-moon-village/screen-1.webp",
							alt: "A farm with crops beside a red-roofed house",
							caption: "Home farm",
							width: 1280,
							height: 720,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
						{
							url: "/projects/morning-moon-village/screen-2.webp",
							alt: "Farm management with a cow pen",
							caption: "Farm management",
							width: 1280,
							height: 720,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
						{
							url: "/projects/morning-moon-village/screen-6.webp",
							alt: "A crowd of players in the town square",
							caption: "The town square",
							width: 1280,
							height: 720,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
						{
							url: "/projects/morning-moon-village/marketplace.webp",
							alt: "The NFT marketplace page",
							caption: "The marketplace",
							width: 1280,
							height: 720,
							fit: MediaFit.Cover,
							tone: MediaTone.Ui,
						},
					],
				},
			},
			{
				type: BlockType.Contributions,
				params: { label: "What I built" },
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Game client",
							description: "3D farming and exploring",
						},
						{
							name: "Go game server",
							description: "Shop, resource spawning",
						},
						{
							name: "MongoDB",
							description: "Players, items, farms",
						},
						{
							name: "Bitkub Chain",
							description: "Solidity: DeFi and NFTs",
						},
					],
				},
			},
			{
				type: BlockType.Challenge,
				params: {
					label: "The hard part",
					items: [
						{
							problem:
								"Five years of server code written by other people.",
							approach:
								"Read it until new features fit its grain instead of fighting it, then shipped new systems without breaking a live economy.",
						},
						{
							problem: "Real value moves through NFTs and DeFi.",
							approach:
								"Tested how each feature works and how it could be abused, before every release.",
						},
						{
							problem:
								"Server features had to land in step with the client team.",
							approach:
								"Agreed the contract between server and client first, then built to it.",
						},
					],
				},
			},
			{
				type: BlockType.Statement,
				params: {
					text: "Reading five years of someone else's code is a skill. I have it now.",
				},
			},
			{
				type: BlockType.Showcase,
				params: {
					label: "The hunters",
					url: "/projects/morning-moon-village/hunting.webp",
					alt: "Three villagers ready to hunt with a snake on a shoulder",
					caption: "Into the wild zone",
					width: 821,
					height: 503,
					fit: MediaFit.Contain,
					tone: MediaTone.Photo,
				},
			},
			{ type: BlockType.Links, params: { label: "See it" } },
		],
	},
	{
		id: "aads",
		num: "0006",
		name: "AADS",
		full: "Army Air Defense System",
		kind: MotifKind.Radar,
		side: ProjectSide.BehindTheScenes,
		tags: [
			"TypeScript",
			"Node.js",
			"Electron",
			"Socket.io",
			"Radar protocols",
		],
		categories: ["platforms"],
		stack: ["typescript", "node.js", "electron", "socket.io", "mysql"],
		about: "Military software for Thailand that turns raw surveillance-radar signals into a live air picture. Operators see every track, flag suspect aircraft, run training scenarios, and talk to each other over voice and text.",
		role: [
			"Owned the server as the full-stack developer on a four-person research lab team: Electron, React, Node.js with TypeScript, Socket.io and MySQL.",
			"Decoded the TRML and DR127ADV radar message formats into tracks.",
			"Built the socket link that streams tracks and control changes to every operator console.",
			"Built IP-based access control for consoles, plus operator voice calls and messaging.",
		],
		artUrl: "/projects/aads/operator-console.webp",
		position: "Full-stack developer (intern)",
		period: "Jun 2022 – Jun 2023",
		team: "Bangkok University research lab",
		lifecycle: ProjectLifecycle.Research,
		platforms: ["Desktop"],
		chains: [],
		links: [],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: { tagline: "Radar, decoded." },
			},
			{ type: BlockType.Overview, params: { label: "Overview" } },
			{
				type: BlockType.Showcase,
				params: {
					label: "Operator console",
					url: "/projects/aads/operator-console.webp",
					alt: "Dark map of Thailand with radar rings and aircraft tracks",
					caption:
						"The operator map: radar coverage rings and live tracks",
					width: 1280,
					height: 724,
					fit: MediaFit.Cover,
					tone: MediaTone.Ui,
				},
			},
			{
				type: BlockType.FeatureGrid,
				params: {
					label: "What it does",
					items: [
						"Real-time aircraft tracking from surveillance radars",
						"Simulated aircraft for training and rehearsing real situations",
						"Alerts for suspect aircraft, so operators react sooner",
						"One-click track states, like friend or enemy",
						"Voice calls and messaging between operators",
						"Access control based on where an operator logs in from",
					],
				},
			},
			{
				type: BlockType.Contributions,
				params: { label: "What I built" },
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Radars",
							description: "TRML and DR127ADV feeds",
						},
						{
							name: "Decoder",
							description: "One thread per radar",
						},
						{
							name: "Socket.io",
							description: "Tracks and controls, both ways",
						},
						{
							name: "Operator consoles",
							description: "Map, alerts, voice, messages",
						},
						{
							name: "MySQL",
							description: "Sites, settings, history",
						},
					],
				},
			},
			{
				type: BlockType.Showcase,
				params: {
					label: "Server console",
					url: "/projects/aads/server-console.webp",
					alt: "Server log listing registered commands and radar threads",
					caption: "The server I built, starting a thread per radar",
					width: 998,
					height: 599,
					fit: MediaFit.Cover,
					tone: MediaTone.Ui,
				},
			},
			{
				type: BlockType.Challenge,
				params: {
					label: "The hard part",
					items: [
						{
							problem:
								"Dense binary protocols, and the data never stops.",
							approach:
								"A streaming decoder per radar on its own thread, so every feed decodes exactly and on time.",
						},
						{
							problem: "The socket link must stay private.",
							approach:
								"IP-based access in front of every console connection.",
						},
					],
				},
			},
			{
				type: BlockType.Statement,
				params: { text: "Binary in. Air picture out." },
			},
		],
	},
];
