// Generated by scripts/build-portfolio/index.ts from content/ME.md. Edit the source, then run bun run build:portfolio.
import {
	BlockTone,
	BlockType,
	DeviceView,
	HeaderVariant,
	MockScreen,
	MotifKind,
	ProjectSide,
} from "@/api/types/portfolio/enums";
import type { Project } from "@/api/types/portfolio/project";
export const projects: Project[] = [
	{
		id: "morning-moon-pocket",
		num: "0001",
		name: "Morning Moon Pocket",
		full: "Morning Moon Pocket",
		kind: MotifKind.Pixel,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "MongoDB", "Solidity", "DeFi", "Soneium"],
		categories: ["games", "on-chain"],
		stack: [
			"golang",
			"mongodb",
			"solidity",
			"defi",
			"soneium",
			"mission system",
			"shop system",
			"client",
			"data",
			"smart contract",
		],
		about: "Morning Moon Village, rebuilt for phones. The same farming and resource gathering on a touch-first screen, with the whole server side rewritten for global players on the Soneium chain.",
		role: [
			"Rewrote the server side in Golang and MongoDB with a new database schema and optimised code, so it scales to far more players.",
			"Moved the old features onto the new architecture and kept the live ones working.",
			"Added new features such as a shop system and a mission system, and kept every player in sync in real time.",
			"Rewrote most of the Solidity smart contracts for the game’s DeFi mechanics, so they are safe, efficient and fit the new architecture.",
			"Worked with the client-side team so server features felt smooth on mobile.",
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: {
					variant: HeaderVariant.Vertical,
					title: "Morning Moon Pocket",
					subtitle: "Morning Moon Pocket",
					index: "0001",
					discipline: ProjectSide.BehindTheScenes,
					tags: ["Golang", "MongoDB", "Solidity", "DeFi", "Soneium"],
					kind: MotifKind.Pixel,
				},
			},
			{
				type: BlockType.Chips,
				params: {
					label: "The brief",
					title: "Rebuilt.",
					text: "The whole server side, rebuilt for mobile and for global players on the Soneium chain.",
					items: ["Golang", "MongoDB", "Solidity", "Soneium"],
				},
			},
			{
				type: BlockType.Lineage,
				params: {
					label: "Lineage",
					from: "Morning Moon Village",
					fromId: "morning-moon-village",
					to: "Morning Moon Pocket",
					text: "Same farming loop, new pocket-sized client, a rebuilt server side and rewritten contracts underneath.",
				},
			},
			{
				type: BlockType.Gallery,
				params: {
					label: "Screens",
					items: [
						{
							kind: MotifKind.Pixel,
							screen: MockScreen.Main,
							view: DeviceView.Phone,
							caption: "Farm",
						},
						{
							kind: MotifKind.Pixel,
							screen: MockScreen.Alt,
							view: DeviceView.Phone,
							caption: "Missions",
						},
					],
					caption: "Illustrative mock",
				},
			},
			{
				type: BlockType.NumberedList,
				params: {
					label: "What I did",
					items: [
						"Rewrote the server side in Golang and MongoDB with a new database schema and optimised code, so it scales to far more players.",
						"Moved the old features onto the new architecture and kept the live ones working.",
						"Added new features such as a shop system and a mission system, and kept every player in sync in real time.",
						"Rewrote most of the Solidity smart contracts for the game’s DeFi mechanics, so they are safe, efficient and fit the new architecture.",
						"Worked with the client-side team so server features felt smooth on mobile.",
					],
				},
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Mobile client",
							description: "Pocket-sized farm",
						},
						{
							name: "Go services",
							description: "Shop, missions, more",
						},
						{
							name: "MongoDB",
							description: "Players and progress",
						},
						{
							name: "Solidity on Soneium",
							description: "Rewritten DeFi contracts",
						},
					],
				},
			},
			{
				type: BlockType.StackCards,
				params: {
					label: "What was hard",
					items: [
						"Rewriting old features on a new architecture while keeping the old ones working took careful planning with the client-side team.",
						"More players with the same feel, on a short timeline, left a lot of testing and debugging to keep the new build stable.",
						"The smart contracts had to get faster and stay just as secure, which left no room for shortcuts.",
					],
				},
			},
		],
	},
	{
		id: "metal-valley",
		num: "0002",
		name: "Metal Valley",
		full: "Metal Valley",
		kind: MotifKind.Hex,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "MongoDB", "Solidity", "Real-time", "DeFi"],
		categories: ["games", "on-chain"],
		stack: [
			"golang",
			"mongodb",
			"solidity",
			"socket",
			"defi",
			"nft",
			"web3",
			"client",
			"backend",
			"smart contract",
			"blockchain",
		],
		about: "A hybrid game that mixes Web2 gameplay with Web3 ownership. Players are mech hunters on a distant archipelago: they find wandering robots, capture and train them, customise them, and restore them to help humanity again.",
		role: [
			"Built the Golang WebSocket layer that links players to the game, made to stay fast, secure and reliable with many players online.",
			"Built core mechanics such as capturing and training robots.",
			"Kept the socket server and the API server in step by sharing the same MongoDB state.",
			"Wrote most of the Solidity smart contracts for the game’s DeFi mechanics on the Bitkub chain, focused on safety and efficiency.",
			"Built the website and backend that bridge items between the game and the chain, where players manage their assets and NFTs.",
			"Worked with the client-side team so server features fit the game smoothly.",
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: {
					variant: HeaderVariant.Outline,
					title: "Metal Valley",
					subtitle: "Metal Valley",
					index: "0002",
					discipline: ProjectSide.BehindTheScenes,
					tags: [
						"Golang",
						"MongoDB",
						"Solidity",
						"Real-time",
						"DeFi",
					],
					kind: MotifKind.Hex,
				},
			},
			{
				type: BlockType.AboutSplit,
				params: {
					label: "About",
					text: "A hybrid game that mixes Web2 gameplay with Web3 ownership. Players are mech hunters on a distant archipelago: they find wandering robots, capture and train them, customise them, and restore them to help humanity again.",
					kind: MotifKind.Hex,
				},
			},
			{
				type: BlockType.Gallery,
				params: {
					label: "Screens",
					items: [
						{
							kind: MotifKind.Hex,
							screen: MockScreen.Main,
							view: DeviceView.Desktop,
							caption: "Capture",
						},
						{
							kind: MotifKind.Hex,
							screen: MockScreen.Alt,
							view: DeviceView.Desktop,
							caption: "Bridge website",
						},
					],
					caption: "Illustrative mock",
				},
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Game client",
							description: "Explore, capture, train",
						},
						{
							name: "Socket server",
							description: "Real-time, many players",
						},
						{
							name: "Shared MongoDB",
							description: "One state for sockets and API",
						},
						{
							name: "Core mechanics",
							description: "Capture & training system",
						},
						{
							name: "Bridge site + backend",
							description: "Game items ↔ chain assets",
						},
						{
							name: "Smart contracts",
							description: "Solidity — DeFi, NFTs",
						},
					],
				},
			},
			{
				type: BlockType.Timeline,
				params: {
					label: "What I did",
					items: [
						"Built the Golang WebSocket layer that links players to the game, made to stay fast, secure and reliable with many players online.",
						"Built core mechanics such as capturing and training robots.",
						"Kept the socket server and the API server in step by sharing the same MongoDB state.",
						"Wrote most of the Solidity smart contracts for the game’s DeFi mechanics on the Bitkub chain, focused on safety and efficiency.",
						"Built the website and backend that bridge items between the game and the chain, where players manage their assets and NFTs.",
						"Worked with the client-side team so server features fit the game smoothly.",
					],
				},
			},
			{
				type: BlockType.Zigzag,
				params: {
					label: "What was hard",
					items: [
						"Many players at once meant fast and secure sockets, planned for scale from day one.",
						"The networked game state and the game logic both had to be optimised, without drifting apart.",
						"Sharing state between the socket server and the API server, so they always agree.",
						"The smart contracts had to be efficient without giving up any security.",
						"With blockchain mechanics and NFTs in the mix, testing and debugging never stopped until the game was stable.",
					],
				},
			},
		],
	},
	{
		id: "evermoon-socialfi",
		num: "0003",
		name: "Evermoon SocialFi",
		full: "Evermoon SocialFi",
		kind: MotifKind.Orbit,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "MongoDB", "NFTs", "Web3", "Missions"],
		categories: ["platforms", "on-chain"],
		stack: ["golang", "mongodb", "nft", "web3", "mission system", "client"],
		about: "Evermoon SocialFi is a platform from Evermoon that rewards people for taking part. Users join monthly quests, complete social media tasks and earn Moon Power (XP) to unlock rewards. With Web3 built in, active users can also collect $EVM tokens, NFTs and exclusive content. The campaign has since ended.",
		role: [
			"Built the server side of the platform in Golang and MongoDB, including the mission system and the quest engine for monthly quests and social-task verification.",
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: {
					variant: HeaderVariant.Center,
					title: "Evermoon SocialFi",
					subtitle: "Evermoon SocialFi",
					index: "0003",
					discipline: ProjectSide.BehindTheScenes,
					tags: ["Golang", "MongoDB", "NFTs", "Web3", "Missions"],
					kind: MotifKind.Orbit,
				},
			},
			{
				type: BlockType.Chips,
				params: {
					label: "About",
					title: "$EVM",
					text: "Evermoon SocialFi is a platform from Evermoon that rewards people for taking part. Users join monthly quests, complete social media tasks and earn Moon Power (XP) to unlock rewards. With Web3 built in, active users can also collect $EVM tokens, NFTs and exclusive content. The campaign has since ended.",
					items: [
						"Monthly quests",
						"Social tasks",
						"Moon Power XP",
						"NFT rewards",
					],
				},
			},
			{
				type: BlockType.Mock,
				params: {
					label: "Quest board",
					kind: MotifKind.Orbit,
					screen: MockScreen.Main,
					view: DeviceView.Desktop,
					caption: "Illustrative mock",
				},
			},
			{
				type: BlockType.Quote,
				params: {
					text: "Built the server side of the platform in Golang and MongoDB, including the mission system and the quest engine for monthly quests and social-task verification.",
					cite: "What I did",
				},
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Platform",
							description: "Tasks and activities",
						},
						{
							name: "Mission system",
							description: "Quests, social tasks, XP",
						},
						{ name: "Rewards", description: "$EVM tokens, NFTs" },
					],
				},
			},
			{
				type: BlockType.Quote,
				params: {
					text: "The quest engine had to work hand in hand with the client-side team, so testing and communication mattered as much as the code.",
					cite: "Challenge",
					tone: BlockTone.Invert,
				},
			},
		],
	},
	{
		id: "estic-ai",
		num: "0004",
		name: "Estic AI",
		full: "Estic AI",
		kind: MotifKind.Pins,
		side: ProjectSide.OnScreen,
		tags: ["Generative AI", "Maps"],
		categories: ["platforms"],
		stack: [
			"generative ai",
			"map",
			"client",
			"server-side",
			"backend",
			"data",
		],
		about: "Estic AI is a real estate platform that helps you find a home by simply talking to it. It pairs generative AI with detailed local data, so every search comes with context, not just listings. It offers features such as conversational search, hyper-local insights, climate-risk simulation, white-label chatbots, and a data marketplace for licensing-grade real estate datasets.",
		role: [
			"Developed the client-side of the platform as a freelance frontend developer with Tetragram: the map, the search and the interface people use every day, in React and TypeScript.",
			"Worked with the server-side team so the screens stayed fast with real data behind them.",
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: {
					variant: HeaderVariant.SplitRev,
					title: "Estic AI",
					subtitle: "Estic AI",
					index: "0004",
					discipline: ProjectSide.OnScreen,
					tags: ["Generative AI", "Maps"],
					kind: MotifKind.Pins,
				},
			},
			{
				type: BlockType.Gallery,
				params: {
					label: "Screens",
					items: [
						{
							kind: MotifKind.Pins,
							screen: MockScreen.Main,
							view: DeviceView.Desktop,
							caption: "Map search",
						},
						{
							kind: MotifKind.Pins,
							screen: MockScreen.Alt,
							view: DeviceView.Phone,
							caption: "Conversation",
						},
					],
					caption: "Illustrative mock",
				},
			},
			{
				type: BlockType.AboutSplit,
				params: {
					label: "About",
					text: "Estic AI is a real estate platform that helps you find a home by simply talking to it. It pairs generative AI with detailed local data, so every search comes with context, not just listings",
					list: [
						"Conversational search",
						"Hyper-local insights",
						"Climate-risk simulation",
						"White-label chatbots",
						"A data marketplace for licensing-grade real estate datasets",
					],
				},
			},
			{
				type: BlockType.StackCards,
				params: {
					label: "What I did",
					items: [
						"Developed the client-side of the platform as a freelance frontend developer with Tetragram: the map, the search and the interface people use every day, in React and TypeScript.",
						"Worked with the server-side team so the screens stayed fast with real data behind them.",
					],
				},
			},
			{
				type: BlockType.NumberedList,
				params: {
					label: "What was hard",
					items: [
						"The product used new tools and patterns, so the UI framework needed careful groundwork.",
						"The map shows 4k+ pins zoomed out and about 1k+ zoomed in, so it asks the backend for only the pins in the current view and clusters them on the client with Leaflet.",
						"Many features and data sources meant security had to be part of every integration.",
					],
				},
			},
		],
	},
	{
		id: "morning-moon-village",
		num: "0005",
		name: "Morning Moon Village",
		full: "Morning Moon Village",
		kind: MotifKind.Moon,
		side: ProjectSide.BehindTheScenes,
		tags: ["Golang", "Solidity", "DeFi", "NFTs", "In-game shop"],
		categories: ["games", "on-chain"],
		stack: [
			"golang",
			"solidity",
			"defi",
			"nft",
			"shop system",
			"client",
			"server-side",
			"backend",
			"smart contract",
			"blockchain",
		],
		about: "A farming game with real DeFi yield farming inside it. Players grow crops, gather resources and learn how yield farming works while they play, earning tokens along the way. NFTs add a competitive edge, and the cute 3D world keeps it friendly.",
		role: [
			"Learned a Golang backend that had grown for five years under other hands, then extended it with features such as the new shop system and resource spawning.",
			"Connected the game to the blockchain so its DeFi mechanics and NFTs work in play.",
			"Wrote Solidity smart contracts for the DeFi mechanics, built with security in mind.",
			"Worked closely with the client-side team, so new features landed in the game without friction.",
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: {
					variant: HeaderVariant.Center,
					title: "Morning Moon Village",
					subtitle: "Morning Moon Village",
					index: "0005",
					discipline: ProjectSide.BehindTheScenes,
					tags: [
						"Golang",
						"Solidity",
						"DeFi",
						"NFTs",
						"In-game shop",
					],
					kind: MotifKind.Moon,
				},
			},
			{
				type: BlockType.AboutSplit,
				params: {
					label: "About",
					text: "A farming game with real DeFi yield farming inside it. Players grow crops, gather resources and learn how yield farming works while they play, earning tokens along the way. NFTs add a competitive edge, and the cute 3D world keeps it friendly.",
					kind: MotifKind.Moon,
				},
			},
			{
				type: BlockType.Mock,
				params: {
					label: "Farm & shop",
					kind: MotifKind.Moon,
					screen: MockScreen.Main,
					view: DeviceView.Desktop,
					caption: "Illustrative mock",
				},
			},
			{
				type: BlockType.StackCards,
				params: {
					label: "What I did",
					items: [
						"Learned a Golang backend that had grown for five years under other hands, then extended it with features such as the new shop system and resource spawning.",
						"Connected the game to the blockchain so its DeFi mechanics and NFTs work in play.",
						"Wrote Solidity smart contracts for the DeFi mechanics, built with security in mind.",
						"Worked closely with the client-side team, so new features landed in the game without friction.",
					],
				},
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{ name: "Game client", description: "3D farming game" },
						{
							name: "Game server",
							description: "Shop, resource spawning",
						},
						{
							name: "Smart contracts",
							description: "Solidity — DeFi, NFTs",
						},
					],
				},
			},
			{
				type: BlockType.Quote,
				params: {
					text: "Real money moves through NFTs and DeFi, so testing went deep on both how things work and how they could be abused.",
					cite: "Hardest part",
					tone: BlockTone.Invert,
				},
			},
			{
				type: BlockType.NumberedList,
				params: {
					label: "What was hard",
					items: [
						"Understanding five years of server-side code written by others, so new features fit instead of fighting it.",
						"The DeFi mechanics live in Solidity smart contracts, so every contract had to be secure before it went live.",
						"Real money moves through NFTs and DeFi, so testing went deep on both how things work and how they could be abused.",
					],
				},
			},
		],
	},
	{
		id: "aads",
		num: "0006",
		name: "AADS",
		full: "Army Air Defense System",
		kind: MotifKind.Radar,
		side: ProjectSide.BehindTheScenes,
		tags: ["Real-time", "Radar protocols", "Encryption", "Maps"],
		categories: ["platforms"],
		stack: [
			"socket",
			"trml",
			"encrypt",
			"map",
			"client",
			"real-time",
			"backend",
			"data",
		],
		about: "Software that turns raw radar signals into a live air picture for military operators in Thailand. It tracks aircraft from surveillance radars, lets operators talk and message each other, and raises an alert when an aircraft looks hostile. Access to each control depends on where the operator logs in from.",
		role: [
			"Built the TypeScript backend as the full-stack developer on a four-person team, from my internship at the university research lab.",
			"Decoded radar messages in the TRML and DR127ADV protocols and turned them into readable tracks on a map.",
			"Built the socket link between server and client, so every operator sees updates and control changes in real time.",
			"Designed the operator screen: a live map with zoom and pan, voice calls, messaging and alerts for suspect aircraft.",
		],
		blocks: [
			{
				type: BlockType.ProjectHeader,
				params: {
					variant: HeaderVariant.Split,
					title: "AADS",
					subtitle: "Army Air Defense System",
					index: "0006",
					discipline: ProjectSide.BehindTheScenes,
					tags: [
						"Real-time",
						"Radar protocols",
						"Encryption",
						"Maps",
					],
					kind: MotifKind.Radar,
				},
			},
			{
				type: BlockType.Quote,
				params: {
					text: "Software that turns raw radar signals into a live air picture for military operators in Thailand.",
					cite: "Brief",
				},
			},
			{
				type: BlockType.Mock,
				params: {
					label: "Operator console",
					kind: MotifKind.Radar,
					screen: MockScreen.Main,
					view: DeviceView.Desktop,
					caption: "Illustrative mock",
				},
			},
			{
				type: BlockType.Architecture,
				params: {
					label: "How it works",
					nodes: [
						{
							name: "Surveillance radars",
							description: "Encoded track messages",
						},
						{
							name: "Decoder",
							description: "TRML · DR127ADV → readable",
						},
						{
							name: "Node.js socket server",
							description: "Real-time state, both ways",
						},
						{
							name: "Operator UI",
							description: "Map, voice, messaging, alerts",
						},
					],
				},
			},
			{
				type: BlockType.FeatureGrid,
				params: {
					label: "What it does",
					items: [
						"Real-time aircraft tracking from surveillance radars",
						"Fake aircraft for training and for rehearsing real situations",
						"Access control based on the operator's IP address",
						"Voice calls and encrypted messaging between operators",
						"Alerts for suspect aircraft, so operators react sooner",
						"One-click state changes, like marking an aircraft as friend or enemy",
						"A map you can zoom and pan, with alert settings each operator can tune",
					],
				},
			},
			{
				type: BlockType.Timeline,
				params: {
					label: "What I did",
					items: [
						"Built the TypeScript backend as the full-stack developer on a four-person team, from my internship at the university research lab.",
						"Decoded radar messages in the TRML and DR127ADV protocols and turned them into readable tracks on a map.",
						"Built the socket link between server and client, so every operator sees updates and control changes in real time.",
						"Designed the operator screen: a live map with zoom and pan, voice calls, messaging and alerts for suspect aircraft.",
					],
				},
			},
			{
				type: BlockType.Zigzag,
				params: {
					label: "What was hard",
					items: [
						"The radar protocols are dense and the data never stops, so decoding had to be both exact and fast.",
						"The socket link had to stay up and stay private, which meant planning the network and its security together.",
						"Operators work under pressure. The screen went through many rounds of testing until it felt obvious to use.",
					],
				},
			},
		],
	},
];
